<a href="https://colab.research.google.com/github/celinecresswell/learning_ML_datasci/blob/main/titanicMachineLearningFromDisaster.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import relevant libraries
import numpy as np #For mathematical functions
import pandas as pd #For handling pandas and dataframe
import matplotlib.pyplot as plt #For data visualisation
import seaborn as sns #For data visualisation

In [2]:
df =pd.read_csv('/content/train.csv')

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
df.shape

(891, 12)

In [10]:
#Check for null values
is_null = df.isnull().sum()
col_sum = df.shape[0]   #We only need the sum of one column length
per_null = is_null/col_sum *100
print(per_null)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64


Over 50% of cabin is missing, remove cabin

In [18]:
df.drop('Cabin', axis =1, inplace= True)

#axis =1 means columns ie columns will be dropped
# inplace = True means that the df when called will now no longer have what was dropped

In [20]:
#Check that the column has been removed
df.shape

(891, 11)

In [21]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [24]:
!pip install fancyimpute

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 154 kB 39.7 MB/s 
  Created wheel for fancyimpute: filename=fancyimpute-0.7.0-py3-none-any.whl size=29899 sha256=2d1f23694c930fe4b336a7e398aaba9da2493092531561760d17b13e05dd20ff
  Stored in directory: /root/.cache/pip/wheels/e3/04/06/a1a7d89ef4e631ce6268ea2d8cde04f7290651c1ff1025ce68
  Created wheel for knnimpute: filename=knnimpute-0.1.0-py3-none-any.whl size=11353 sha256=bc7bc3132793c1def89a886675fdb300f0d3716e22edb08ff3b96c2cd2fe6d5c
  Stored in directory: /root/.cache/pip/wheels/72/21/a8/a045cacd9838abd5643f6bfa852c0796a99d6b1494760494e0
Successfully built fancyimpute knnimpute


In [25]:
# Age still has over 10% missing data, we don't know why those values were missing so we cannot delete the rows with missing data
# ie the MCAR (missing because of random) assumption cannot be made.
#The data needs to imputed

#install the library for imputing
from fancyimpute import IterativeImputer

In [30]:
mice_imputer = IterativeImputer()

df['Age'] = mice_imputer.fit_transform(df[['Age']])

new_isNull = df.isnull().sum()
total = df['Age'].shape
per = new_isNull/ total *100
print(per)

PassengerId    0.000000
Survived       0.000000
Pclass         0.000000
Name           0.000000
Sex            0.000000
Age            0.000000
SibSp          0.000000
Parch          0.000000
Ticket         0.000000
Fare           0.000000
Embarked       0.224467
dtype: float64


In [32]:
df['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [34]:
#replace the nan values with the majority value (Since the nan value percent is so small)
df['Embarked'].fillna('S', inplace = True)

In [36]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [39]:
df.dtypes

PassengerId    float64
Survived       float64
Pclass         float64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [42]:
#import library to convert the object data types
from sklearn.preprocessing import LabelEncoder
#Initialise
le = LabelEncoder()

In [43]:
# convert object type features into numbers
df['Name']= le.fit_transform(df['Name'])
df['Sex']= le.fit_transform(df['Sex'])
df['Ticket']= le.fit_transform(df['Ticket'])
df['Embarked']= le.fit_transform(df['Embarked'])

In [47]:
X = df.drop('Survived', axis = 1)
y = df['Survived']

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size = 0.2, random_state = 1)

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
sS = StandardScaler()
#Only scale the data after it has been split and only apply to the training data
#Using any information from the test set before or during training can lead to potential bias in the performance


In [53]:
X_train = sS.fit_transform(X_train)


In [54]:
#import libraries which will give analysis tools
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [55]:
#create a function which will create a model and provide the outputs for analysis
# This will save code later on
def create_model(model):
  model.fit(X_train, y_train) #model training
  y_pred = model.predict(X_test) #model testing
  #both metrics will use the y_test and y_pred
  print(classification_report(y_test, y_pred))
  print(confusion_matrix(y_test, y_pred))
  return model


In [58]:
#First model - Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
decisionTreeClassifier = DecisionTreeClassifier(random_state =1 , max_depth = 10)
dtc_model = create_model(decisionTreeClassifier)

              precision    recall  f1-score   support

         0.0       0.60      0.99      0.75       106
         1.0       0.75      0.04      0.08        73

    accuracy                           0.60       179
   macro avg       0.68      0.52      0.41       179
weighted avg       0.66      0.60      0.47       179

[[105   1]
 [ 70   3]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [67]:
#Second model - Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
randomForestClassifier = RandomForestClassifier(n_estimators = 13, max_features = 8, random_state = 42)
rfc_model = create_model(randomForestClassifier)

              precision    recall  f1-score   support

         0.0       0.62      0.87      0.72       106
         1.0       0.53      0.22      0.31        73

    accuracy                           0.60       179
   macro avg       0.58      0.54      0.52       179
weighted avg       0.58      0.60      0.55       179

[[92 14]
 [57 16]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


In [71]:
#Third model - logistic regression classifier
from sklearn.linear_model import LogisticRegression
logisticRegression = LogisticRegression()

In [72]:
create_model(logisticRegression)

              precision    recall  f1-score   support

         0.0       0.60      0.88      0.71       106
         1.0       0.46      0.15      0.23        73

    accuracy                           0.58       179
   macro avg       0.53      0.51      0.47       179
weighted avg       0.54      0.58      0.51       179

[[93 13]
 [62 11]]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


LogisticRegression()

The decision tree classifier worked best of the three and should be used.